oss-apps/split-pro

src/components/Expense/ExpensePage.tsx
src/components/Friend/Settleup.tsx
src/components/Layout/MainLayout.tsx
src/components/ui/avatar.tsx
src/hooks/useEnableAfter.ts
src/pages/_app.tsx
src/pages/account.tsx
src/pages/activity.tsx
src/pages/add.tsx
src/pages/balances.tsx
src/pages/balances/[friendId].tsx
src/pages/balances/[friendId]/expenses/[expenseId].tsx
src/pages/balances/expenses.tsx
src/pages/expenses/[expenseId].tsx
src/pages/groups.tsx
src/pages/groups/[groupId].tsx
src/pages/groups/[groupId]/expenses/[expenseId].tsx
src/server/api/routers/user.ts
src/server/auth.ts
src/types.ts

More details here: https://x.com/KM_Koushik_/status/1765964881415799082?s=20

Move getServerProps to client.

---

src/components/Friend/DeleteFriend.tsx
src/pages/balances/[friendId].tsx
src/server/api/routers/user.ts

Add delete friend

---

src/components/Friend/DeleteFriend.tsx
src/pages/balances/[friendId].tsx
src/pages/groups.tsx
src/pages/groups/[groupId].tsx
src/server/api/routers/group.ts
src/server/api/services/splitService.ts

Add group delete and group leave option

---

src/components/AddExpense/AddExpensePage.tsx
src/components/group/AddMembers.tsx
src/components/group/GroupMyBalance.tsx
src/pages/add.tsx
src/pages/groups.tsx
src/pages/groups/[groupId].tsx

Add outstanding balance in group view

---

src/components/AddExpense/AddExpensePage.tsx
src/pages/_app.tsx
src/pages/add.tsx

Avoid loading when currency is updated in Add expense screen

---

src/components/Friend/Settleup.tsx
src/pages/activity.tsx

Fix numbers not correctly showing in activity and settel up expense page

---

src/pages/account.tsx
src/server/api/routers/user.ts
src/server/api/services/splitService.ts

Add download splitpro data

---

src/components/AddExpense/AddExpensePage.tsx

Convert comma to decimal for amount input

---

public/sitemap.xml

Add sitemap

---

src/server/api/routers/user.ts
src/server/mailer.ts

Send invite email if user is invited by a friend

---

next.config.js
package.json
pnpm-lock.yaml
prisma/migrations/20240330050427_add_imported_from_splitiwise_user/migration.sql
prisma/migrations/20240330061939_add_splitwise_group_id/migration.sql
prisma/migrations/20240330064009_add_splitwise_group_id_unique/migration.sql
prisma/schema.prisma
src/components/ui/checkbox.tsx
src/pages/account.tsx
src/pages/import-splitwise.tsx
src/server/api/routers/user.ts
src/server/api/services/splitService.ts
src/types.ts

Add import from splitwise option

---

src/components/Expense/ExpensePage.tsx
src/pages/groups/[groupId].tsx
src/server/api/routers/group.ts

Show expense date instead of created date in groups

---

src/components/AddExpense/AddExpensePage.tsx
src/pages/groups/[groupId].tsx

Allow adding expense to empty group

---

.env.example
src/components/Account/SubscribeNotification.tsx
src/components/NotificationModal.tsx
src/env.js
src/server/notification.ts

Make web push optional and add env details

---

src/pages/groups.tsx
src/pages/groups/[groupId].tsx

change user groups icon to be a Plus sign

---

src/components/group/NoMembers.tsx

- Related issues: https://github.com/oss-apps/split-pro/issues/102

fix: Group invite link on NoMembers screen

---

next.config.js

fix images not working in self-hodted env

---

pnpm-lock.yaml
src/components/Account/SubmitFeedback.tsx
src/components/Account/ThemeSelect.tsx
src/components/AddExpense/SplitTypeSection.tsx
src/components/AddExpense/UserInput.tsx
src/components/InstallApp.tsx
src/components/Layout/MainLayout.tsx
src/components/ui/drawer.tsx
src/pages/_app.tsx
src/pages/account.tsx
src/pages/activity.tsx
src/pages/auth/signin.tsx
src/pages/balances.tsx
src/pages/groups/[groupId].tsx
src/pages/import-splitwise.tsx
src/pages/index.tsx
src/server/api/routers/group.ts
src/store/addStore.ts
src/styles/globals.css

Here is the dark and light theme support.
- Added theme selector on account settings page.
- Fixed all style where light mode was not working.
- Ability to change between "system", "dark" and "light"
Screenshots:

🚀  Add dark and light support

---

src/server/mailer.ts

Correction to a missing closing angle bracket.

Missing closing angle bracket

---

src/components/AddExpense/AddExpensePage.tsx
src/pages/add.tsx
src/store/addStore.ts

Fix expense date resetting to today when editing

---

src/store/addStore.ts

Fix equal split with one participant resetting on edit

---

src/pages/groups.tsx

Fix: group balance showing empty currency

---

src/components/AddExpense/AddExpensePage.tsx
src/components/AddExpense/CategoryPicker.tsx
src/components/AddExpense/CurrencyPicker.tsx
src/components/AddExpense/SplitTypeSection.tsx
src/components/AddExpense/UploadFile.tsx
src/components/group/NoMembers.tsx
src/pages/groups/[groupId].tsx
src/server/db.ts
src/store/addStore.ts

The issue was caused by lack of memoization and functions rerunning on component rerenders. Memoization was applied, huge addExpense component split and also I fixed some bugs that I noticed along the way. Closes #63

Fix 63 attachments resetting split

---

src/components/Account/UpdateDetails.tsx
src/pages/account.tsx
src/pages/groups/[groupId].tsx
src/server/api/routers/group.ts

Feat 147 edit group name

---

src/pages/groups/[groupId].tsx
src/server/api/services/notificationService.ts
src/server/notification.ts
worker/index.ts

Fix 215 expense notification redirect

---

src/components/Expense/BalanceList.tsx
src/components/Expense/ExpenseList.tsx
src/components/Friend/GroupSettleup.tsx
src/components/Friend/Settleup.tsx
src/pages/groups/[groupId].tsx
src/utils/strings.ts

Feat 237 group settlement

---

src/pages/auth/signin.tsx
src/pages/join-group.tsx

Closes #54 
The group links now work when a user authenticates in between and redirect to the said group page.

Fix 54 group invite redirect

---

src/components/Friend/GroupSettleup.tsx
src/pages/groups/[groupId].tsx
src/server/api/routers/group.ts

Feat 159 remove member from group

---

src/components/group/AddMembers.tsx

Mention searching members by name and always show email button

---

prisma/seed.ts
src/components/AddExpense/AddExpensePage.tsx
src/components/AddExpense/UploadFile.tsx
src/components/Expense/ExpenseList.tsx
src/components/Friend/DeleteFriend.tsx
src/components/Friend/GroupSettleup.tsx
src/components/Friend/Settleup.tsx
src/pages/balances.tsx
src/pages/balances/[friendId].tsx
src/pages/groups/[groupId].tsx
src/pages/groups/[groupId]/expenses/[expenseId].tsx
src/server/api/root.ts
src/server/api/routers/expense.ts
src/server/api/routers/group.ts
src/server/api/routers/user.ts
src/server/api/services/splitService.ts
src/types/expense.types.ts

Split the expense handling into a separate TRPC router. The main goal is to reduce code duplication.

Expense router refactor

---

src/components/AddExpense/CategoryPicker.tsx
src/components/Expense/ExpensePage.tsx
src/components/Friend/GroupSettleup.tsx
src/components/Friend/Settleup.tsx
src/components/ui/categoryIcons.tsx
src/lib/category.ts
src/lib/type.ts
src/store/addStore.ts

Closes #255 
Adds 3 new categories: Hotel, Insurance, Bike
Changed duplicate icons: supplies, rent, taxes

Task 255 add more categories

---

src/pages/add.tsx

Set category when loading expense data

Fix category loading on expense edit

---

next-i18next.config.js
public/locales/de/account_details.json
public/locales/de/account_page.json
public/locales/de/activity_page.json
public/locales/de/add_page.json
public/locales/de/balances.json
public/locales/de/balances_page.json
public/locales/de/common.json
public/locales/de/expense_details.json
public/locales/de/friend_details.json
public/locales/de/groups_details.json
public/locales/de/groups_page.json
public/locales/de/import_splitwise.json
public/locales/de/index.json
public/locales/de/signin.json
src/utils/i18n/client.ts

Added German localization files

Add German locale

---

public/locales/de/common.json
public/locales/de/expense_details.json
public/locales/de/groups_details.json
public/locales/en/expense_details.json

Some corrections to german localization

Corrections to german locale

---

public/locales/pl/common.json
public/locales/pl/expense_details.json
src/components/AddExpense/SplitTypeSection.tsx
src/components/Expense/ExpenseDetails.tsx

Identified two locations which should use "dativus" case for "you"

Use correct case (dativus) in translations

---

docker/prod/compose.yml

refine hostname comment

---

src/components/Friend/Settleup.tsx
src/pages/balances/[friendId].tsx

Fix locale strings and remove currentUser prop in SettleUp

---

package.json
pnpm-lock.yaml
src/components/Account/AccountButton.tsx
src/components/Account/DownloadAppDrawer.tsx
src/components/Account/LanguagePicker.tsx
src/components/Account/SubmitFeedback.tsx
src/components/Account/SubscribeNotification.tsx
src/components/Expense/BalanceList.tsx
src/components/ui/dialog.tsx
src/components/ui/drawer.tsx
src/pages/account.tsx
src/pages/balances.tsx
src/pages/home.tsx

Fix 359 account page alignment

---

src/utils/number.test.ts
src/utils/numbers.ts

Reverts oss-apps/split-pro#403 due to CI errors

Revert "fix for Negative expenses with decimals- #370"
